# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

title: Who's Dustin
name: whosdustin.com
description: > #
              Front-end developer with an extensive knowledge in user experience.
              Seven years design experience and once nominated for a CSS Design
              Award. Actively working as a Front-end developer for Bisk Education.
author:
  name: Dustin Delatore
  email: dustin@delatore.me
  available:
twitter_username: whos_dustin
github_username:  whosdustin
dribbble_username: whosdustin

navigation:
 - title: Articles
   url: /articles
# - title: Projects
#   url: /projects
 - title: About
   url: /about

collections:
  projects:
    output: true
    permalink: /:path/

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

gems:
  - jekyll-sitemap
  - jekyll-contentblocks

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Additional Settings
permalink: none

# Markdown library
markdown: kramdown
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

highlighter: rouge
