---
title: Whos Dustin
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  talks:
    title: Talks
    output: true
    permalink: "/talks/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    categories: ''
    author: Dustin Delatore
    is_post: true
email: dustin@delatore.me
description: Dustin is a Ui developer located in Orlando, FL, and have extensive knowledge
  in user experience. On top of that, I have years of design experience and was once
  nominated for a CSS Design Award. Currently, working at Three21.
baseurl: ''
url: http://whosdustin.com
twitter_username: whos_dustin
github_username: whosdustin
dribbble_username: whosdustin
gems:
- jekyll-sitemap
- jekyll-redirect-from
permalink: "/articles/:title/"
highlighter: rouge
markdown: kramdown
