---
title: Whos Dustin
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  talks:
    title: Talks
    output: true
    permalink: "/talks/:path/"
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    categories: ''
    author: Dustin Delatore
    is_post: true
- scope:
    path: ''
    type: pages
  values:
    layout: page
    description: ''
- scope:
    path: ''
    type: work
  values:
    link: ''
- scope:
    path: ''
    type: products
  values:
    layout: product
    permalink: "/products/:title/"
    name: ''
    price: 0.0
    sku: ''
    image: ''
    weight: 0.0
email: dustin@delatore.me
description: 'Dustin turns analog ideas into digital masterpieces. Dustin spends his working hours building a rich tapestry of e-commerce Shopify themes. On the side, he travel, illustrates, and YouTubes.

'
baseurl:
url: https://whosdustin.com
twitter_username: whos_dustin
github_username: whosdustin
dribbble_username: whosdustin
instagram_username: whos.dustin
youtube_channel: dustindelatore
medium_username: '@whosdustin'
owner:
  name: Dustin Delatore
header_pages:
- articles.html
- talks.html
gems:
- jekyll-sitemap
- jekyll-redirect-from
- jemoji
permalink: "/articles/:title/"
highlighter: rouge
markdown: kramdown
